export type AIcon =
  "/images/calculus-128.ico" |
  "/images/calculus-128.webp" |
  "/images/calculus-180.png" |
  "/images/calculus-180.webp" |
  "/images/calculus-200.webp" |
  "/images/calculus-300.webp" |
  "/images/calculus-32.webp" |
  "/images/calculus-400.webp" |
  "/images/calculus-64.webp" |
  "/images/calculus-96.webp" |
  "/images/deep-numpy-128.ico" |
  "/images/deep-numpy-128.webp" |
  "/images/deep-numpy-180.png" |
  "/images/deep-numpy-180.webp" |
  "/images/deep-numpy-200.webp" |
  "/images/deep-numpy-300.webp" |
  "/images/deep-numpy-32.webp" |
  "/images/deep-numpy-400.webp" |
  "/images/deep-numpy-64.webp" |
  "/images/deep-numpy-96.webp" |
  "/images/linalg-128.ico" |
  "/images/linalg-128.webp" |
  "/images/linalg-180.png" |
  "/images/linalg-180.webp" |
  "/images/linalg-200.webp" |
  "/images/linalg-300.webp" |
  "/images/linalg-32.webp" |
  "/images/linalg-400.webp" |
  "/images/linalg-64.webp" |
  "/images/linalg-96.webp" |
  "/images/magnifying-glass-128.ico" |
  "/images/magnifying-glass-128.webp" |
  "/images/magnifying-glass-180.png" |
  "/images/magnifying-glass-180.webp" |
  "/images/magnifying-glass-200.webp" |
  "/images/magnifying-glass-300.webp" |
  "/images/magnifying-glass-32.webp" |
  "/images/magnifying-glass-400.webp" |
  "/images/magnifying-glass-64.webp" |
  "/images/magnifying-glass-96.webp" |
  "/images/orange-cat-robot-128.ico" |
  "/images/orange-cat-robot-128.webp" |
  "/images/orange-cat-robot-180.png" |
  "/images/orange-cat-robot-180.webp" |
  "/images/orange-cat-robot-200.webp" |
  "/images/orange-cat-robot-300.webp" |
  "/images/orange-cat-robot-32.webp" |
  "/images/orange-cat-robot-400.webp" |
  "/images/orange-cat-robot-64.webp" |
  "/images/orange-cat-robot-96.webp";
export const $aicon = (icon: AIcon) => icon;
